
inventory:
  max_position: 50.0
  max_imbalance: 10.0

quote:
  num_levels: 5
  total_quote_size: 100.0
  min_spread: 0.0001
  vol_impact: 1.0

order:
  market_symbol: "BTC/USD [WETH-USDC]"
  collateral_token: "USDC"
  initial_collateral: 10.0
  debug_mode: true

oms:
  max_active_orders: 20
  order_timeout: 60.0
  slippage_percent: 0.01
